// Homework2/xioliu/src/charts/piechart.jsx
import React from "react";
import * as d3 from "d3";
import './piechart.css'
import Dropdown from "react-bootstrap/Dropdown";

export default function Piechart({data}) {
    const svgRef = React.useRef(null);
    const width = 300;
    const height = 300;
    const margin = 10;
    const [selection, setSelection] = React.useState('All');

    function processData(data) {
        let dist = {Loyal: 0, Disloyal: 0};

        for (let d in data) {
            let row = data[d];
            if (selection !== 'All') {
                if (row['Gender'] !== selection) {
                    continue;
                }
            }

            if (row['Customer Type'] === 'Loyal Customer') {
                dist.Loyal += 1;
            } else {
                dist.Disloyal += 1;
            }
        }
        return dist
    }

    function plotPieChart(){
        let dist = processData(data);
        // console.log(dist)
        let radius = Math.min(width, height) / 2 - margin

        d3.select(svgRef.current).selectAll('path').remove();
        d3.select(svgRef.current).selectAll('text').remove();


        const svg = d3.select(svgRef.current).append('g')
            .attr("transform", "translate(" + (width  / 2 + 40) + "," + (height / 2 + 20) + ")");;
        let color = d3.scaleOrdinal()
            .range(d3.schemeSet2);

        let legendColor = {Loyal: '#008F8C', Disloyal: '#F24405'}
        // console.log(legendColor)

        let pie = d3.pie()
            .value((d) => d[1]);

        let data_ready = pie(Object.entries(dist));
        // console.log(data_ready)

        const arcGenerator = d3.arc()
            .innerRadius(20)
            .outerRadius(radius)

        svg
            .selectAll('mySlices')
            .data(data_ready)
            .join('path')
            .attr('d', arcGenerator)
            .attr('fill', function(d){ return(legendColor[d.data[0]]) })
            .attr("stroke", "black")
            .attr('x', width / 2)
            .attr('y', height / 2)
            .style("stroke-width", "2px")
            .style("opacity", 0.7)

        svg
            .selectAll('mySlices')
            .data(data_ready)
            .join('text')
            .text(function(d){ return d.data[0] + ':' + d.data[1]})
            .attr("transform", function(d) { return `translate(${arcGenerator.centroid(d)})`})
            .style("text-anchor", "middle")
            .style("font-size", 14)

        svg.append('circle')
            .attr("cx", width - 80)
            .attr("cy", 80)
            .attr('r', 6)
            .style('fill', legendColor.Loyal)
        svg.append('text')
            .attr('x', width - 65)
            .attr('y', 83)
            .attr('text-anchor', 'start')
            .text('Loyal')

        svg.append('circle')
            .attr("cx", width - 80)
            .attr("cy", 100)
            .attr('r', 6)
            .style('fill', legendColor.Disloyal)
        svg.append('text')
            .attr('x', width - 65)
            .attr('y', 103)
            .attr('text-anchor', 'start')
            .text('DisLoyal')
    }

    React.useEffect(() => {
        if (data !== null){
            plotPieChart();
        }
    }, [data, selection])

    if (data === null) {
        return(<div></div>)
    } else {
        return (
            <div className={'container'}>
                Customer Proportion
                <div className={"DropdownP"}>
                    <Dropdown>
                        <Dropdown.Toggle id={"dropdown-basic"} variant="secondary" size={'sm'}>
                            {selection}
                        </Dropdown.Toggle>

                        <Dropdown.Menu variant="dark">
                            <Dropdown.Item onClick={() => setSelection('All')}>All</Dropdown.Item>
                            <Dropdown.Item onClick={() => setSelection('Male')}>Male</Dropdown.Item>
                            <Dropdown.Item onClick={() => setSelection('Female')}>Female</Dropdown.Item>
                        </Dropdown.Menu>
                    </Dropdown>
                </div>

                <div className={'pie-container'}>
                    <svg ref={svgRef} width={'100%'} height={'100%'} />
                </div>
            </div>


        )
    }


}

// Homework3/orzwang/src/views/components/piechart.vue
<template>
    <div id="pie-chart-container">
    </div>
</template>


<script>
import { defineComponent } from 'vue';
import * as d3 from "d3";
import testData from "../../assets/data/test.json";
//const data = await d3.csv(".csv");
//console.log(data);
export default {
    name: "PieChart",
    mounted() {
        console.log(testData);
        let localData = testData['data'];
        this.DrawPieChart(testData, {
            name: d => d.y,
            value: d => d.x,
            width: 640 ,
            height: 400
        })
    },
    methods:{
        DrawPieChart(data, {
            name = ([y]) => y,
            value = ([, x]) => x,
            title,
            width = 640,
            height = 400,
            innerRadius = 0,
            outerRadius = Math.min(width, height) / 2,
            labelRadius = (innerRadius * 0.2 + outerRadius * 0.8),
            format = '',
            names,
            colors,
            stroke = innerRadius > 0 ? "none" : "white",
            strokeWidth = 1,
            strokeLinejoin = "round",
            padAngle = stroke === "none" ? 1 / outerRadius : 0,
        } = {}) {
            const N = d3.map(data, name).slice(0, 15);
            const V = d3.map(data, value).slice(0, 15);
            const I = d3.range(N.length).filter(i => !isNaN(V[i]));
 
            if (names === undefined) names = N;
            names = new d3.InternSet(names);
 
            if (colors === undefined) colors = d3.schemeSpectral[names.size];
            if (colors === undefined) colors = d3.quantize(t => d3.interpolateSpectral(t * 0.8 + 0.1), names.size);
 
            const color = d3.scaleOrdinal(names, colors);
 
            if (title === undefined) {
                const formatValue = d3.format(format);
                title = i => `${N[i]}\n${formatValue(V[i])}万亿`;
            } else {
                const O = d3.map(data, d => d);
                const T = title;
                title = i => T(O[i], i, data);
            }
 
            const arcs = d3.pie().padAngle(padAngle).sort(null).value(i => V[i])(I);
            const arc = d3.arc().innerRadius(innerRadius).outerRadius(outerRadius);
            const arcLabel = d3.arc().innerRadius(labelRadius).outerRadius(labelRadius);
  
            const svg = d3.selectAll("#pie-chart-container")
                .append("svg")
                .attr("width", width)
                .attr("height", height)
                .attr("viewBox", [-width / 2, -height / 2, width, height])
                .attr("style", "max-width: 100%; height: auto; height: intrinsic;");
 
            svg.append("g")
                .attr("stroke", stroke)
                .attr("stroke-width", strokeWidth)
                .attr("stroke-linejoin", strokeLinejoin)
                .selectAll("path")
                .data(arcs)
                .join("path")
                .attr("fill", d => color(N[d.data]))
                .attr("d", arc)
                .append("title")
                .text(d => title(d.data));
 
            svg.append("g")
                .attr("font-family", "sans-serif")
                .attr("font-size", 10)
                .attr("text-anchor", "middle")
                .selectAll("text")
                .data(arcs)
                .join("text")
                .attr("transform", d => `translate(${arcLabel.centroid(d)})`)
                .selectAll("tspan")
                .data(d => {
                    const lines = `${title(d.data)}`.split(/\n/);
                    return (d.endAngle - d.startAngle) > 0.20 ? lines : lines.slice(0, 1);
                })
                .join("tspan")
                .attr("x", 0)
                .attr("y", (_, i) => `${i * 1.1}em`)
                .attr("font-weight", (_, i) => i ? null : "bold")
                .text(d => d);
        }
    }
}
</script>
